[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# This plugin will create the sitemap.xml for you automatically!
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
